//
import { v4 as uuid } from 'uuid';
import { IWidget } from 'src/types/product';
import { getDesc, getValue } from '../langWidgets/_langWidgets';

// ----------------------------------------------------------------------

export const HoverButton: IWidget = {
  id: uuid(),
  name: 'HoverButton',
  order: 0,
  drop: 0,
  category: '',
  company: '',
  open: false,
  label: {
    id: 'hoverButton',
    name: 'Hover Button',
    color: 'black',
  },
  childs: [
    {
      id: 'Head',
      open: true,
      show: true,
      attributes: {
        GoToTop: {
          feId: 'GoToTop',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('GoToTop'),
          value: getValue('GoToTop'),
        },
        ShowContactMail: {
          feId: 'ShowContactMail',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('ShowContactMail'),
          value: getValue('ShowContactMail'),
        },
        ContactMail: {
          feId: 'ContactMail',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('ContactMail'),
          value: getValue('ContactMail'),
        },
        ShowRebuy: {
          feId: 'ShowRebuy',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('ShowRebuy'),
          value: getValue('ShowRebuy'),
        },
        HoverButtonProductURL: {
          feId: 'HoverButtonProductURL',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('HoverButtonProductURL'),
          value: getValue('HoverButtonProductURL'),
        },
        DiscountCode: {
          feId: 'DiscountCode',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('DiscountCode'),
          value: getValue('DiscountCode'),
        },
        DiscountCodeDescription: {
          feId: 'DiscountCodeDescription',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('DiscountCodeDescription'),
          value: getValue('DiscountCodeDescription'),
        },
      },
    },
    {
      id: 'Cover',
      open: false,
      show: true,
      attributes: {
        ShowCover: {
          feId: 'ShowCover',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('ShowCover'),
          value: getValue('ShowCover'),
        },
        ShowPanorama: {
          feId: 'ShowPanorama',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('ShowPanorama'),
          value: getValue('ShowPanorama'),
        },
        CoverImage: {
          feId: 'CoverImage',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('CoverImage'),
          value: getValue('CoverImage'),
        },
        CoverImgFile: {
          feId: 'CoverImgFile',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('CoverImgFile'),
          value: getValue('CoverImgFile'),
        },
      },
    },
  ],
  style: {
    Orientation: {
      name: 'Orientation',
      value: ['right'],
    },
    ShowHover: {
      name: 'ShowHover',
      value: ['X'],
    },
  },
};
