//
import { v4 as uuid } from 'uuid';
import { IWidget } from 'src/types/product';
import { getDesc, getValue } from '../langWidgets/_langWidgets';

// ----------------------------------------------------------------------

export const ProductInfo: IWidget = {
  id: uuid(),
  name: 'ProductInfo',
  order: 0,
  drop: 0,
  category: 'Required',
  company: '',
  open: false,
  label: {
    id: 'productinfo',
    name: 'Product Info',
    color: 'black',
  },
  childs: [
    {
      id: 'Head',
      open: true,
      show: true,
      attributes: {
        WidgetHeadline_ProductInformation: {
          feId: 'WidgetHeadline_ProductInformation',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_ProductInformation'),
          value: getValue('WidgetHeadline_ProductInformation'),
        },
        ProductInfoDescription: {
          feId: 'ProductInfoDescription',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('ProductInfoDescription'),
          value: getValue('ProductInfoDescription'),
        },
        ProductInfoBasicInformation: {
          feId: 'ProductInfoBasicInformation',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('ProductInfoBasicInformation'),
          value: getValue('ProductInfoBasicInformation'),
        },
      },
    },
    {
      id: 'Nutrients',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Nutrients: {
          feId: 'WidgetHeadline_Nutrients',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Nutrients'),
          value: getValue('WidgetHeadline_Nutrients'),
        },
        ProductInfoNutrients: {
          feId: 'ProductInfoNutrients',
          template: true,
          keyValueTemp: [
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
            { keyTemp: true, valueTemp: false },
          ],
          translate: false,
          data: true,
          valueType: 'keyValue',
          name: getDesc('ProductInfoNutrients'),
          value: getValue('ProductInfoNutrients'),
        },
        ProductInfoCustomFields: {
          feId: 'ProductInfoCustomFields',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('ProductInfoCustomFields'),
          value: getValue('ProductInfoCustomFields'),
        },
        ServingUnit: {
          feId: 'ServingUnit',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('ServingUnit'),
          value: getValue('ServingUnit'),
        },
        ReferenceQuantity: {
          feId: 'ReferenceQuantity',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('ReferenceQuantity'),
          value: getValue('ReferenceQuantity'),
        },
        ServingSize: {
          feId: 'ServingSize',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('ServingSize'),
          value: getValue('ServingSize'),
        },
        EnableServingSize: {
          feId: 'EnableServingSize',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('EnableServingSize'),
          value: getValue('EnableServingSize'),
        },
      },
    },
    {
      id: 'Ingredients',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Ingredients: {
          feId: 'WidgetHeadline_Ingredients',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Ingredients'),
          value: getValue('WidgetHeadline_Ingredients'),
        },
        ProductInfoIngredients: {
          feId: 'ProductInfoIngredients',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'list',
          name: getDesc('ProductInfoIngredients'),
          value: getValue('ProductInfoIngredients'),
        },
        ProductInfoAllergens: {
          feId: 'ProductInfoAllergens',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'list',
          name: getDesc('ProductInfoAllergens'),
          value: getValue('ProductInfoAllergens'),
        },
        ProductInfoNotesAndWarnings: {
          feId: 'ProductInfoNotesAndWarnings',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('ProductInfoNotesAndWarnings'),
          value: getValue('ProductInfoNotesAndWarnings'),
        },
      },
    },
    {
      id: 'Distributor',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Distributor: {
          feId: 'WidgetHeadline_Distributor',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Distributor'),
          value: getValue('WidgetHeadline_Distributor'),
        },
        ProductInfoResponsibleDistributor: {
          feId: 'ProductInfoResponsibleDistributor',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('ProductInfoResponsibleDistributor'),
          value: getValue('ProductInfoResponsibleDistributor'),
        },
        PostalCode: {
          feId: 'PostalCode',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('PostalCode'),
          value: getValue('PostalCode'),
        },
        City: {
          feId: 'City',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('City'),
          value: getValue('City'),
        },
        Street: {
          feId: 'Street',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('Street'),
          value: getValue('Street'),
        },
        Link: {
          feId: 'Link',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('Link'),
          value: getValue('Link'),
        },
        Email: {
          feId: 'Email',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('Email'),
          value: getValue('Email'),
        },
        ProducedIn: {
          feId: 'ProducedIn',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: true,
          valueType: 'value',
          name: getDesc('ProducedIn'),
          value: getValue('ProducedIn'),
        },
      },
    },
    {
      id: 'Storage',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Storage: {
          feId: 'WidgetHeadline_Storage',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Storage'),
          value: getValue('WidgetHeadline_Storage'),
        },
        ProductInfoStorageFields: {
          feId: 'ProductInfoStorageFields',
          template: true,
          keyValueTemp: [
            { keyTemp: false, valueTemp: false },
            { keyTemp: false, valueTemp: false },
          ],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('ProductInfoStorageFields'),
          value: getValue('ProductInfoStorageFields'),
        },
      },
    },
  ],
  style: {},
};
