//
import { v4 as uuid } from 'uuid';
import { IWidget } from 'src/types/product';
import { getDesc, getValue } from '../langWidgets/_langWidgets';

// ----------------------------------------------------------------------

export const Sustainability: IWidget = {
  id: uuid(),
  name: 'Sustainability',
  order: 0,
  drop: 0,
  category: 'Sustainability',
  company: '',
  open: false,
  label: {
    id: 'sustainability',
    name: 'Sustainability',
    color: 'black',
  },
  childs: [
    {
      id: 'Head',
      open: true,
      show: true,
      attributes: {
        WidgetHeadline_Sustainability: {
          feId: 'WidgetHeadline_Sustainability',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Sustainability'),
          value: getValue('WidgetHeadline_Sustainability'),
        },
        SustainabilityDescription: {
          feId: 'SustainabilityDescription',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('SustainabilityDescription'),
          value: getValue('SustainabilityDescription'),
        },
      },
    },
    {
      id: 'Initiatives',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Initiatives: {
          feId: 'WidgetHeadline_Initiatives',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Initiatives'),
          value: getValue('WidgetHeadline_Initiatives'),
        },
        SubheadlineInitiatives: {
          feId: 'SubheadlineInitiatives',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('SubheadlineInitiatives'),
          value: getValue('SubheadlineInitiatives'),
        },
        InitiativePicture: {
          feId: 'InitiativePicture',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('InitiativePicture'),
          value: getValue('InitiativePicture'),
        },
        InitiativeFilename: {
          feId: 'InitiativeFilename',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('InitiativeFilename'),
          value: getValue('InitiativeFilename'),
        },
        InitiativeShowPicture: {
          feId: 'InitiativeShowPicture',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('InitiativeShowPicture'),
          value: getValue('InitiativeShowPicture'),
        },
        InitiativeDesc: {
          feId: 'InitiativeDesc',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('InitiativeDesc'),
          value: getValue('InitiativeDesc'),
        },
      },
    },
    {
      id: 'Truecost',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Truecost: {
          feId: 'WidgetHeadline_Truecost',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Truecost'),
          value: getValue('WidgetHeadline_Truecost'),
        },
        TrueCostProductDesc: {
          feId: 'TrueCostProductDesc',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostProductDesc'),
          value: getValue('TrueCostProductDesc'),
        },
        TrueCostProductUVP: {
          feId: 'TrueCostProductUVP',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostProductUVP'),
          value: getValue('TrueCostProductUVP'),
        },
        TrueCostProduct: {
          feId: 'TrueCostProduct',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostProduct'),
          value: getValue('TrueCostProduct'),
        },
        TrueCostCompareDesc: {
          feId: 'TrueCostCompareDesc',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostCompareDesc'),
          value: getValue('TrueCostCompareDesc'),
        },
        TrueCostCompareUVP: {
          feId: 'TrueCostCompareUVP',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostCompareUVP'),
          value: getValue('TrueCostCompareUVP'),
        },
        TrueCostCompare: {
          feId: 'TrueCostCompare',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'value',
          name: getDesc('TrueCostCompare'),
          value: getValue('TrueCostCompare'),
        },
        TrueCostCauses: {
          feId: 'TrueCostCauses',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('TrueCostCauses'),
          value: getValue('TrueCostCauses'),
        },
        TrueCostStudy: {
          feId: 'TrueCostStudy',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('TrueCostStudy'),
          value: getValue('TrueCostStudy'),
        },
        TrueCostStudyName: {
          feId: 'TrueCostStudyName',
          template: true,
          keyValueTemp: [],
          translate: false,
          data: false,
          valueType: 'value',
          name: getDesc('TrueCostStudyName'),
          value: getValue('TrueCostStudyName'),
        },
      },
    },
    {
      id: 'Co2',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Co2: {
          feId: 'WidgetHeadline_Co2',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Co2'),
          value: getValue('WidgetHeadline_Co2'),
        },
        Co2Values: {
          feId: 'Co2Values',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('Co2Values'),
          value: getValue('Co2Values'),
        },
      },
    },
    {
      id: 'Water',
      open: false,
      show: true,
      attributes: {
        WidgetHeadline_Water: {
          feId: 'WidgetHeadline_Water',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: false,
          valueType: 'value',
          name: getDesc('WidgetHeadline_Water'),
          value: getValue('WidgetHeadline_Water'),
        },
        WaterValues: {
          feId: 'WaterValues',
          template: true,
          keyValueTemp: [],
          translate: true,
          data: true,
          valueType: 'keyValue',
          name: getDesc('WaterValues'),
          value: getValue('WaterValues'),
        },
      },
    },
  ],
  style: {},
};
